//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalogConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Songs = new HashSet<Songs>();
        }
    
        public int AlbumID { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public int Rating { get; set; }
        public int ArtistID { get; set; }
        public int GenreID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Songs> Songs { get; set; }
    }
}
